apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eka-system

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - redis.yaml
  - rabbitmq.yaml
  - qdrant.yaml
  - neo4j.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
